apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: metrics
    secureJsonData:
      basicAuthPassword: metrics
    jsonData:
      httpMethod: POST
      timeInterval: 5s